// generateMarkdown function -  README.md
generateMarkdown = (answers) => {
    return `
<h1 align="center">${answers.projectTitle}</h1>


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

![badge](https://img.shields.io/badge/license-${answers.license}-green)<br />

## Description
${answers.description}

## Table of Contents

- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [Description](#description)
- [Tests](#tests)
- [License](#license)
- [Screenshots](#screenshots)
- [Questions](#questions)
- [Contact](#contact)

<a name="installation"></a>
## Installation :floppy_disk:
${answers.installation}

<a name="usage"></a>
## Usage :computer:
${answers.usage}

<a name="contributing"></a>
## Contributing :family:
${answers.contributing}

## Screenshots
Include logo/demo screenshot etc. ${answers.screenshots}

<a name="tests"></a>
## Tests :pencil2:
${answers.tests}

## License
![badge](https://img.shields.io/badge/license-${answers.license}-green)
<br />
This application is covered by the ${answers.license} license. 

<a name="questions"></a>
## Questions :question:
${answers.questions}<br />

<a name="contact"></a>
## Contact
<br />
Find me on :octocat: : [${answers.username}](https://github.com/${answers.username})

<br />
*****

Email me with any questions :email: : ${answers.email}
*****
<br />

__This README was generated by [README-generator](https://github.com/michaelmw17/w8homework) with :heartpulse:__
*****`;
  }
  
  module.exports = generateMarkdown;

  //https://nodejs.org/api/modules.html#modules_module_exports