// generateReadMe function -  README.md
function generateReadMe(answers) {
    return `
<h1 align="center">${answers.projectTitle}</h1>
*****
  
[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

![badge](https://img.shields.io/badge/license-${answers.license}-green)<br />

## Description
${answers.description}

## Table of Contents
*****
- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [Description](#description)
- [Tests](#tests)
- [License](#license)
- [Questions](#questions)
- [node.js] - I/O for the backend

## :floppy_disk: <strong>Installation<strong />
${answers.installation}

## :computer: How to use?
${answers.usage}

## :family: Contributing 
${answers.contributing}

## Screenshots
Include logo/demo screenshot etc.

## Tests
✏️ ${answers.tests}

## License
![badge](https://img.shields.io/badge/license-${answers.license}-green)
<br />
This application is covered by the <strong>${answers.license}<strong/> license. 

## Questions :question:
${answers.questions}<br />
<br />
Find me on :octocat: : [${answers.username}](https://github.com/${answers.username})
*****
<br />

Email me with any questions :email: : ${answers.email}
*****
<br />

#### Anything else that seems useful
*****

_This README was generated by [README-generator](https://github.com/michaelmw17/w8homework) with :heart:_
    `;
  }
  
  module.exports = generateReadMe;