// generateReadMe function -  README.md
  generateReadMe = (answers) => {
    return `
<h1 align="center">${answers.projectTitle}</h1>


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

![badge](https://img.shields.io/badge/license-${answers.license}-green)<br />

## Description
${answers.description}

## Table of Contents

- [Installation](#installation)
- [Usage](#usage)
- [Contributing](#contributing)
- [Description](#description)
- [Tests](#tests)
- [License](#license)
- [Screenshots](#screenshots)
- [Questions](#questions)

## Installation :floppy_disk:
<a name="installation"></a>
${answers.installation}

## Usage :computer:
<a name="usage"></a>
${answers.usage}

## Contributing :family:
<a name="contributing"></a>
${answers.contributing}

## Screenshots
Include logo/demo screenshot etc. ${answers.screenshots}

## Tests :pencil2:
<a name="tests"></a>
${answers.tests}

## License
![badge](https://img.shields.io/badge/license-${answers.license}-green)
<br />
This application is covered by the ${answers.license} license. 

## Questions :question:
<a name="questions"></a>
${answers.questions}<br />
<br />
Find me on :octocat: : [${answers.username}](https://github.com/${answers.username})
*****
<br />

Email me with any questions :email: : ${answers.email}
*****
<br />

__This README was generated by [README-generator](https://github.com/michaelmw17/w8homework) with :heartpulse:__
*****`;
  }
  
  module.exports = generateReadMe;

  //https://nodejs.org/api/modules.html#modules_module_exports